# Copyright (c) 2019, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "3"
services:
  fluent-bit:
    image: fluent/fluent-bit
    volumes:
      - ./conf/fluentbit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./conf/fluentbit/parsers.conf:/fluent-bit/etc/parsers.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"   
  db:
    container_name: postgresdb
    image: postgres:13
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./conf/postgre/scripts/postgresinitscriptssetup.sql:/docker-entrypoint-initdb.d/postgresinitscriptssetup.sql  
    env_file:
      - ./secret-stuff.env
    logging:
          driver: fluentd  
          options:
            tag: postgresdb
    ports:
      - "5463:5432"
    healthcheck:
      #test: ["CMD-SHELL", "pg_isready -U postgres"]
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
  is-as-km:
    build: ./dockerfiles/is-as-km
    healthcheck:
      test: ["CMD", "nc", "-z","localhost", "9443"]
      interval: 10s
      start_period: 180s
      retries: 3
    depends_on:
      db:
        condition: service_healthy      
    logging:
      driver: fluentd
      options:
        tag: is-as-km      
    volumes:
      - ./conf/is-as-km:/home/wso2carbon/wso2-config-volume
    ports:
      - "9444:9443"
      - "9764:9763"
  api-manager:
    build: ./dockerfiles/apim
    healthcheck:
      test: ["CMD", "nc", "-z","localhost", "9443"]
      interval: 10s
      start_period: 180s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
      is-as-km:
        condition: service_healthy
    logging:
      driver: fluentd
      options:
        tag: api-manager       
    volumes:
      - ./conf/apim:/home/wso2carbon/wso2-config-volume
    ports:
      - "9443:9443"
      - "8280:8280"
      - "8243:8243"